Repository jayk-gupta/web-resources-project, pull requests merged in 2023-08, with the labels that each got.

#555 Added animation on all cards images
  src/components/Card.jsx
  src/index.css
Labels: gssoc23, level1

#571 bug-fix for activeTab issue #559
  src/components/nav/NavItem.jsx
  src/components/nav/NavUI.jsx
Labels: gssoc23, level1, status: approved

#566 Added scroll to top to every page
  src/App.jsx
  src/components/ScrollToTopButton.jsx
Labels: gssoc23, level1

#576 New CSS Resource
  src/database/challenges/css.json
Labels: gssoc23, addition, level1

#490 feat: Added Edabit Object Details in javascript.json File
  src/database/tools/javascript.json
Labels: gssoc23, addition, level1

#549 Tailwind CSS section added
  src/components/books/Index.jsx
  src/components/challenges/Index.jsx
  src/components/filter/index.jsx
  src/components/tools/Index.jsx
  src/components/videos/Index.jsx
  src/components/websites/Index.jsx
  src/database/books/tailwindcss.json
  src/database/challenges/tailwindcss.json
  src/database/tools/tailwindcss.json
  src/database/videos/tailwindcss.json
  src/database/websites/tailwindcss.json
Labels: gssoc23, addition, level2, status: approved

#581 Fixed React in website category
  src/database/websites/reactjs.json
Labels: bug, gssoc23, level1, status: approved

#577 bug-fix-572 search issue
  src/components/nav/SideNav.jsx
  src/components/nav/SideNavMobile.jsx
Labels: bug, gssoc23, level1

#551 Editor added
  src/App.jsx
  src/components/editor/Index.jsx
  src/components/nav/Nav.jsx
  src/components/nav/NavItem.jsx
  src/database/editor/css.json
  src/database/editor/html.json
  src/database/editor/javascript.json
  src/database/editor/reactjs.json
Labels: gssoc23, addition, level2, status: approved

#563 [DOCS]: Update Readme
  README.md
Labels: documentation, gssoc23, level1

#565 books are added
  src/database/books/reactjs.json
Labels: gssoc23, addition, level1

#586 css animation added
  src/database/tools/css.json
Labels: gssoc23, addition, level1

#590 wrong data deleted from website and java script tutorial is added[BUG is solved]
  src/database/websites/html.json
  src/database/websites/javascript.json
Labels: bug, gssoc23, level1

#592 feat: Added DevDocs.io website Details in 5 Files in websites Category Section
  src/database/websites/css.json
  src/database/websites/html.json
  src/database/websites/javascript.json
  src/database/websites/reactjs.json
  src/database/websites/tailwindcss.json
Labels: gssoc23, addition, level1, status: approved

#616 Improvised ScrollBar
  src/index.css
Labels: gssoc23, UI, level1

#614 enhanced README.md
  README.md
Labels: documentation, gssoc23, level1

#607 search Feature add #578
  src/components/books/Index.jsx
  src/components/challenges/Index.jsx
  src/components/nav/NavItem.jsx
  src/components/nav/NavUI.jsx
  src/components/nav/SideNav.jsx
  src/components/tools/Index.jsx
  src/components/videos/Index.jsx
  src/components/websites/Index.jsx
Labels: bug, gssoc23, level2

#604 css FLEX GAME IS ADDED
  public/images original/css_flex.png
  src/database/challenges/css.json
Labels: gssoc23, addition, level1

#594 Image path and website link added
  src/database/websites/tailwindcss.json
Labels: bug, gssoc23, level1

#595 tailwind guide website added
  src/database/websites/tailwindcss.json
Labels: gssoc23, level1

#619 codewell added
  src/database/challenges/html.json
Labels: gssoc23, addition, level1

#622 bug-fix #608 for mobile
  src/components/filter/index.jsx
Labels: bug, gssoc23, level1

#623 css resources added
  src/database/challenges/css.json
Labels: gssoc23, addition, level1

#591 feat: Added Programiz Details in html.json and javascript.json Files in websites Category
  src/database/websites/html.json
  src/database/websites/javascript.json
Labels: gssoc23, addition, level1

#626 codewars added
  src/database/challenges/javascript.json
Labels: gssoc23, addition, level1

#627 dev challenges added
  src/database/challenges/javascript.json
Labels: gssoc23, addition, level1

#637 Duplicates Removed
  src/components/nav/NavItem.jsx
Labels: bug, gssoc23, level1

#593 feat: Added Studytonight Details in 3 Files in websites Category
  src/database/websites/css.json
  src/database/websites/html.json
  src/database/websites/javascript.json
Labels: gssoc23, addition, level1

#646 reactjs video is added
  public/images original/reactjs_codewithharry.png
  src/database/videos/reactjs.json
Labels: gssoc23, addition, level1

#647 codestoic
  src/database/videos/reactjs.json
Labels: gssoc23, addition, level1
