Repository jayk-gupta/web-resources-project, pull requests merged in 2023-06, with the labels that each got.

#308 Added badges and back-to-top link in ReadMe.md
  README.md
Labels: GSSoC'23, level-1

#307 added one resource for react
  public/Card Images/website/website.md
  public/images original/react_javatpoint.png
  src/database/websites.json
Labels: GSSoC'23, level-1

#309 Update challenges.json
  src/database/challenges.json
Labels: GSSoC'23, level-1

#275 Added some Javascript Resoruce Website
  pnpm-lock.yaml
  public/Card Images/website/website.md
  src/database/websites.json
Labels: GSSoC'23, level-1

#342 minor UI changes and pnpm, dependencies updated
  .gitpod.yml
  package.json
  pnpm-lock.yaml
  src/components/challenges/Index.jsx
  src/components/filter/index.jsx
  src/components/tools/Index.jsx
  src/components/videos/Index.jsx
  src/components/websites/Index.jsx
  src/database/books.json
Labels: GSSoC'23, level-1

#340 Added the resources for react.js by Parmesh Bhatt
  src/database/videos.json
Labels: GSSoC'23, level-1

#303 Changed Styling for Cards and top navigation bar [ gssoc 2023 ]
  src/components/Card.jsx
  src/components/books/Index.jsx
  src/components/challenges/Index.jsx
  src/components/filter/index.jsx
  src/components/tools/Index.jsx
  tailwind.config.js
Labels: gssoc23, UI, level2

#358 Added dependabot.yml file
  .github/dependabot.yml
Labels: gssoc23, level1

#389 JavaScript Resource
  public/Card Images/website/website.md
  src/database/websites.json
Labels: gssoc23, addition, level1, status: approved

#383 Added the resources of the JavaTpoint - JavaScript by Parmesh Bhatt.
  src/database/websites.json
Labels: gssoc23, addition, level1
