Repository jayk-gupta/web-resources-project, pull requests merged in 2023-05, with the labels that each got.

#58 Create add-resource.md
  .github/ISSUE_TEMPLATE/add-resource.md
Labels: documentation, good first issue, GSSoC'23

#62 Update styling.md
  .github/ISSUE_TEMPLATE/styling.md
Labels: documentation, good first issue, GSSoC'23

#63 add Issue template for Refactor Code
  .github/ISSUE_TEMPLATE/refactor_code.md
Labels: GSSoC'23

#106 added Minify image
  public/Card Images/tools/tools.md
Labels: GSSoC'23

#73 UI Improvements
  src/App.jsx
  src/components/Welcome.jsx
  src/components/books/Books.jsx
  src/components/challenges/Challenges.jsx
  src/components/tools/Tools.jsx
  src/components/videos/Videos.jsx
  src/components/websites/Websites.jsx
Labels: GSSoC'23, level-3

#162 Add Resource in JavaScript Website Section
  public/Card Images/website/website.md
  src/database/Websites/javascript.json
Labels: GSSoC'23, level-2

#256 Added new resources.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  public/Card Images/videos/videos.md
  src/components/Home.jsx
  src/components/books/Index.jsx
  src/components/challenges/Index.jsx
  src/components/tools/Index.jsx
  src/components/videos/Index.jsx
  src/components/websites/Index.jsx
  src/database/videos.json
Labels: GSSoC'23, level-2

#271 Added new resource
  src/database/books.json
Labels: GSSoC'23, level-1
