Repository jayk-gupta/web-resources-project, pull requests merged in 2023-07, with the labels that each got.

#445 [GSSoC'23] Scroll to Top Button Added
  package-lock.json
  package.json
  src/App.jsx
  src/components/ScrollToTopButton.jsx
Labels: gssoc23, level1

#444 [GSSoC'23] Added HTML Book
  src/database/books.json
Labels: gssoc23, level1

#477 restucture the database to load resources faster
  src/App.jsx
  src/components/books/Index.jsx
  src/components/challenges/Index.jsx
  src/components/tools/Index.jsx
  src/components/videos/Index.jsx
  src/components/websites/Index.jsx
  src/database/books.json
  src/database/books/css.json
  src/database/books/html.json
  src/database/books/javascript.json
  src/database/books/reactjs.json
  src/database/challenges.json
  src/database/challenges/css.json
  src/database/challenges/html.json
  src/database/challenges/javascript.json
  src/database/challenges/reactjs.json
  src/database/tools/css.json
  src/database/tools/html.json
  src/database/tools/javascript.json
  src/database/tools/reactjs.json
  src/database/videos.json
  src/database/videos/css.json
  src/database/videos/html.json
  src/database/videos/javascript.json
  src/database/videos/reactjs.json
  src/database/websites.json
  src/database/websites/css.json
  src/database/websites/html.json
  src/database/websites/javascript.json
  src/database/websites/reactjs.json
  src/main.jsx
Labels: enhancement

#487 Cards responsibility
  src/components/books/Index.jsx
  src/components/challenges/Index.jsx
  src/components/tools/Index.jsx
  src/components/videos/Index.jsx
  src/components/websites/Index.jsx
Labels: gssoc23, level1

#491 css palette added
  package-lock.json
  src/database/tools/css.json
Labels: gssoc23, level1

#495 Added Free Code Camp Roadmap
  public/Card Images/website/website.md
  public/images original/react_freecodecamp.png
  src/database/websites/reactjs.json
Labels: gssoc23, addition, level1

#503 Added javascript video resource
  public/Card Images/videos/videos.md
  public/images original/jsv_thapaTechnical.png
  src/database/videos/javascript.json
Labels: gssoc23, addition, level1

#526 color picker added
  src/database/tools/css.json
Labels: gssoc23, addition, level1

#497 Added the video resources of React.js by Clever programmer by Parmesh Bhatt
  src/database/videos/reactjs.json
Labels: gssoc23, addition, level1

#486 tutorial point section is added in website
  public/Card Images/website/website.md
  src/database/websites/reactjs.json
Labels: gssoc23, level1

#546 Added CodePen to Tools Section
  public/Card Images/tools/Screenshot (161).png
  public/Card Images/tools/tools.md
  src/database/tools/css.json
  src/database/tools/html.json
  src/database/tools/javascript.json
Labels: gssoc23, level1

#498 Added the of CSS JavaTpoint by Parmesh Bhatt
  src/database/websites/css.json
Labels: gssoc23, level1

#550 chore: add frontend practice challenge website for html and css ✨
  src/database/challenges/css.json
  src/database/challenges/html.json
Labels: gssoc23, addition, level1

#548 Added Responsiveness
  index.html
  package-lock.json
  src/App.jsx
  src/components/Home.jsx
  src/components/books/Index.jsx
  src/components/challenges/Index.jsx
  src/components/nav/Nav.jsx
  src/components/nav/NavItem.jsx
  src/components/nav/NavUI.jsx
  src/components/nav/SideNav.jsx
  src/components/nav/SideNavMobile.jsx
  src/components/tools/Index.jsx
  src/components/videos/Index.jsx
  src/components/websites/Index.jsx
Labels: gssoc23, UI, level2

#562 Css challenges
  src/database/challenges/css.json
Labels: gssoc23, addition, level1

#567 [DOCS]: Fix typos in README.md
  README.md
Labels: documentation, level1
